# Generated by Django 5.0.7 on 2024-07-30 13:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите электронную почту клиента",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию клиента",
                        max_length=50,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя клиента",
                        max_length=50,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите отчество клиента (при наличии)",
                        max_length=50,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Введите комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Введите тему сообщения",
                        max_length=255,
                        verbose_name="Тема сообщения",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Введите содержание сообщения",
                        verbose_name="Содержание сообщения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Время запуска рассылки",
                        verbose_name="Время запуска",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Раз в день"),
                            ("weekly", "Раз в неделю"),
                            ("monthly", "Раз в месяц"),
                        ],
                        help_text="Периодичность рассылки",
                        max_length=10,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        help_text="Статус рассылки",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("clients", models.ManyToManyField(to="newsletter.client")),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Время попытки отправки письма",
                        verbose_name="Время попытки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        help_text="Статус попытки отправки письма",
                        max_length=10,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True,
                        help_text="Ответ сервера при попытке отправки письма",
                        null=True,
                        verbose_name="Ответ сервера",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.mailing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка отправки",
                "verbose_name_plural": "Попытки отправки",
            },
        ),
    ]
