# Generated by Django 4.2.14 on 2024-08-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_mailing", "Может просматривать рассылки"),
                    ("can_disable_mailing", "Может отключать рассылки"),
                    ("cannot_edit_mailing", "Не может редактировать рассылки"),
                    ("cannot_manage_mailing", "Не может управлять списком рассылок"),
                    ("cannot_change_mailing", "Не может создавать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
