# Generated by Django 4.2.14 on 2024-08-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("can_view_client", "Может просматривать клиентов сервиса")
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("cannot_change_message", "Не может изменять сообщения")
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
